DELETE FROM BOOK_RECIPE;

DELETE FROM DISHTYPE_RECIPE;

DELETE FROM INGREDIENT_RECIPE;


DELETE FROM BOOK;
ALTER TABLE BOOK AUTO_INCREMENT = 1;

DELETE FROM DISHTYPE;
ALTER TABLE DISHTYPE AUTO_INCREMENT = 1;

DELETE FROM INGREDIENT;
ALTER TABLE INGREDIENT AUTO_INCREMENT = 1;

DELETE FROM PUBLICATION;
ALTER TABLE PUBLICATION AUTO_INCREMENT = 1;

DELETE FROM RECIPE;
ALTER TABLE RECIPE AUTO_INCREMENT = 1;
