INSERT INTO RECIPE (TITLE, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Spaghetti Cacio e Pepe', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO RECIPE (TITLE, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Spaghetti alla carbonara', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));


INSERT INTO BOOK (TITLE, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Da Noi', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO BOOK (TITLE, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Sale & Pepe', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));

INSERT INTO BOOK_RECIPE (ID_RECIPE, ID_BOOK) VALUES (1, 1);
INSERT INTO BOOK_RECIPE (ID_RECIPE, ID_BOOK) VALUES (2, 2);


INSERT INTO DISHTYPE (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Pasta', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));

INSERT INTO DISHTYPE_RECIPE (ID_DISHTYPE, ID_RECIPE) VALUES (1, 1);
INSERT INTO DISHTYPE_RECIPE (ID_DISHTYPE, ID_RECIPE) VALUES (1, 2);


INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Uova', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Spaghetti', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Pecorino', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));

INSERT INTO INGREDIENT_RECIPE (ID_INGREDIENT, ID_RECIPE) VALUES (2, 1);
INSERT INTO INGREDIENT_RECIPE (ID_INGREDIENT, ID_RECIPE) VALUES (2, 2);
INSERT INTO INGREDIENT_RECIPE (ID_INGREDIENT, ID_RECIPE) VALUES (1, 2);
INSERT INTO INGREDIENT_RECIPE (ID_INGREDIENT, ID_RECIPE) VALUES (3, 1);


INSERT INTO PUBLICATION (VOLUME, YEAR, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES (9, 2017, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO PUBLICATION (VOLUME, YEAR, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES (5, 2017, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));

UPDATE BOOK_RECIPE SET ID_PUBLICATION = 1 WHERE ID_RECIPE = 1;
UPDATE BOOK_RECIPE SET ID_PUBLICATION = 2 WHERE ID_RECIPE = 2;
