CREATE DATABASE  IF NOT EXISTS `recipe_catalog` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `recipe_catalog`;

DROP TABLE IF EXISTS `DISHTYPE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `DISHTYPE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `CREATION_TIME` DATETIME NOT NULL,
  `LAST_MODIFICATION_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='Dish type table';


DROP TABLE IF EXISTS `INGREDIENT`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `INGREDIENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `CREATION_TIME` DATETIME NOT NULL,
  `LAST_MODIFICATION_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='Ingredient table';
/*!40101 SET character_set_client = @saved_cs_client */;


DROP TABLE IF EXISTS `BOOK`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `BOOK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(50) NOT NULL,
  `CREATION_TIME` DATETIME NOT NULL,
  `LAST_MODIFICATION_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `TITLE_UNIQUE` (`TITLE`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='Book table';
/*!40101 SET character_set_client = @saved_cs_client */;


DROP TABLE IF EXISTS `RECIPE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `RECIPE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(512) NOT NULL,
  `IMAGE_KEY` varchar(1024),
  `CREATION_TIME` DATETIME NOT NULL,
  `LAST_MODIFICATION_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='Recipe table';
/*!40101 SET character_set_client = @saved_cs_client */;


DROP TABLE IF EXISTS `DISHTYPE_RECIPE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `DISHTYPE_RECIPE` (
  `ID_RECIPE` int(11) NOT NULL,
  `ID_DISHTYPE` int(11) NOT NULL,
  PRIMARY KEY (`ID_RECIPE`,`ID_DISHTYPE`),
  KEY `DISHTYPE_RECIPE_FK_2` (`ID_DISHTYPE`),
  CONSTRAINT `DISHTYPE_RECIPE_FK_1` FOREIGN KEY (`ID_RECIPE`) REFERENCES `RECIPE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DISHTYPE_RECIPE_FK_2` FOREIGN KEY (`ID_DISHTYPE`) REFERENCES `DISHTYPE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Relationship table between recipes and dish types';
/*!40101 SET character_set_client = @saved_cs_client */;


DROP TABLE IF EXISTS `INGREDIENT_RECIPE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `INGREDIENT_RECIPE` (
  `ID_RECIPE` int(11) NOT NULL,
  `ID_INGREDIENT` int(11) NOT NULL,
  PRIMARY KEY (`ID_RECIPE`,`ID_INGREDIENT`),
  KEY `INGREDIENT_RECIPE_FK_2` (`ID_INGREDIENT`),
  CONSTRAINT `INGREDIENT_RECIPE_FK_1` FOREIGN KEY (`ID_RECIPE`) REFERENCES `RECIPE` (`ID`),
  CONSTRAINT `INGREDIENT_RECIPE_FK_2` FOREIGN KEY (`ID_INGREDIENT`) REFERENCES `INGREDIENT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Relationship table between recipes and ingredients';
/*!40101 SET character_set_client = @saved_cs_client */;


DROP TABLE IF EXISTS `PUBLICATION`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `PUBLICATION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `VOLUME` int(11) DEFAULT NULL,
  `YEAR` int(11) DEFAULT NULL,
  `CREATION_TIME` DATETIME NOT NULL,
  `LAST_MODIFICATION_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='Publication data table';
/*!40101 SET character_set_client = @saved_cs_client */;


DROP TABLE IF EXISTS `BOOK_RECIPE`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `BOOK_RECIPE` (
  `ID_RECIPE` int(11) NOT NULL,
  `ID_BOOK` int(11) NOT NULL,
  `ID_PUBLICATION` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_RECIPE`),
  KEY `BOOK_RECIPE_FK_2` (`ID_BOOK`),
  KEY `BOOK_RECIPE_FK_3` (`ID_PUBLICATION`),
  CONSTRAINT `BOOK_RECIPE_FK_1` FOREIGN KEY (`ID_RECIPE`) REFERENCES `RECIPE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `BOOK_RECIPE_FK_2` FOREIGN KEY (`ID_BOOK`) REFERENCES `BOOK` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `BOOK_RECIPE_FK_3` FOREIGN KEY (`ID_PUBLICATION`) REFERENCES `PUBLICATION` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;
