INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Chicken', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Ricotta', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Zucchini', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Artichoke', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Mushroom', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Tomato', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Gnocchi', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Rice', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Pork', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO INGREDIENT (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Beef', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));


INSERT INTO RECIPE (TITLE, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Gnocchi al pomodoro', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));


INSERT INTO INGREDIENT_RECIPE (ID_INGREDIENT, ID_RECIPE) VALUES (7, 1);
INSERT INTO INGREDIENT_RECIPE (ID_INGREDIENT, ID_RECIPE) VALUES (6, 1);
