INSERT INTO BOOK (TITLE, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Da Noi', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO BOOK (TITLE, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Sale & Pepe', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO BOOK (TITLE, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('La Cucina Italiana', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO BOOK (TITLE, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Ci Piace Cucinare', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));


INSERT INTO RECIPE (TITLE, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Gnocchi al pomodoro', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));


INSERT INTO BOOK_RECIPE (ID_RECIPE, ID_BOOK) VALUES (1, 2);