CREATE TABLE DISHTYPE (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(50) NOT NULL,
  CREATION_TIME DATETIME NOT NULL,
  LAST_MODIFICATION_TIME DATETIME NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY NAME_UNIQUE (NAME)
);
