INSERT INTO DISHTYPE (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Salad', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO DISHTYPE (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Pasta', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO DISHTYPE (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Risotto', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO DISHTYPE (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Bread', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO DISHTYPE (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Vegetable sides', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO DISHTYPE (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Soup', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO DISHTYPE (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Roast', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO DISHTYPE (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Steak', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO DISHTYPE (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Fish', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
INSERT INTO DISHTYPE (NAME, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Appetizer', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));


INSERT INTO RECIPE (TITLE, CREATION_TIME, LAST_MODIFICATION_TIME) VALUES ('Pasta alle vongole', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));

INSERT INTO DISHTYPE_RECIPE (ID_DISHTYPE, ID_RECIPE) VALUES (2, 1);
INSERT INTO DISHTYPE_RECIPE (ID_DISHTYPE, ID_RECIPE) VALUES (9, 1);